### ISSUE TITLE
Command 

### ISSUE THREAD

**Issue by MalikQasimAli** [Vacxe/Retranslator#8]
I am sorry for this question. Please can you tell me in which terminal (Android Studio or windows CMD) I have to run this line:
$ python3 retranlator.py
Also I installed python 3.6 which is latest.

**Comment by Baawaaji** [comment]
# **Okay I figured it**
Used Android Studio Terminal
and Please correct spelling of "retranlator"
From
$ python3 retranlator.py
to
$ python3 retranslator.py

**Comment by vacxe** [comment]
Today or tomorrow I will migrate this script to python 2.7 bcoz this version supported from box for Unix

**Comment by Vacxe** [comment]
Done thanks!
